# vim: ts=2:sts=2:sw=2:expandtab
version: '3.3'

services:
  traefik:
    image: serubin/traefik # Custom image of traefik - control version in Dockerfile
    build: .
    command: >
      --api
      --docker
      --consul
      --consul.endpoint="consul-leader:8500"
      --loglevel=WARN # Enables the web UI and tells Traefik to listen to docker
    restart: always
    deploy:

      replicas: 1
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - /opt/data/traefik/acme.json:/acme.json
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.tags=traefik-public"
      - "traefik.domain=admin.serubin.net"
      - "traefik.frontend.whiteList.sourceRange=172.110.20.64/32,129.21.39.75/32"
      - "traefik.frontend.rule=Host: admin.serubin.net; PathPrefixStrip: /traefik"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=8080"

networks:
  traefik-public:
    external: true
