[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$qqO466Pi$dW/jJ0Uhi8S.pLOZpg7Az0"
  ]

[http.routers.api]
  rule = "Host(`monitor.your_domain`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.routers]
  [http.routers.to-traefik-1]
  rule = "HostRegexp(`{domain:.+}`)"
  service = traefik-1
  priority = 1

[http.services]
  [http.services.traefik-1.loadBalancer]
    [[http.services.traefik-1.loadBalancer.servers]]
      url = http://traefik-2
