debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
constraints = [ "tag==traefik-public" ]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
swarmMode = true
domain = "cloud.serubin.net"
watch = true
exposedByDefault = false

[acme]
email = "admin@serubin.net"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
